# -*- coding: utf-8 -*-
"""Vivek

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ElAd10DxnJCBFALxYhOB_WI_1RqOQeHQ

Import Libraries
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

"""Load Dataset"""

df = pd.read_csv('/content/code_vulnerabilities.csv')

# Cell 3
df.head()

# Cell 4
df.shape

# Cell 5
df.columns

# Cell 6
df.info()

# Cell 7
df.describe()

# Cell 8
df.isnull().sum()

# Cell 9
df = df.dropna()

# Cell 10
df.duplicated().sum()

# Cell 11
df = df.drop_duplicates()

df.columns = df.columns.str.strip().str.lower().str.replace(" ", "_")

print(df.columns)

target_col = 'vulnerability_type'

X = df.drop(target_col, axis=1)
y = df[target_col]

# Combine useful text columns
df['combined_text'] = df['code_snippet'] + " " + df['preprocessed_tokens']

X = df['combined_text']
y = df['vulnerability_type']

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer(max_features=5000)

X_train = vectorizer.fit_transform(X_train)
X_test = vectorizer.transform(X_test)

from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier()
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

from sklearn.metrics import accuracy_score

print("Accuracy:", accuracy_score(y_test, y_pred))

from sklearn.metrics import classification_report

print(classification_report(y_test, y_pred))

from sklearn.metrics import confusion_matrix
import seaborn as sns
import matplotlib.pyplot as plt

cm = confusion_matrix(y_test, y_pred)

sns.heatmap(cm, annot=True)
plt.title("Confusion Matrix")
plt.show()

df['vulnerability_type'].value_counts().plot(kind='bar')
plt.title("Vulnerability Distribution")
plt.show()

df['code_length'] = df['code_snippet'].apply(len)

plt.hist(df['code_length'], bins=30)
plt.title("Code Snippet Length Distribution")
plt.xlabel("Length")
plt.ylabel("Frequency")
plt.show()

from collections import Counter

all_words = " ".join(df['preprocessed_tokens'].astype(str)).split()
common_words = Counter(all_words).most_common(10)

words = [w[0] for w in common_words]
counts = [w[1] for w in common_words]

plt.bar(words, counts)
plt.title("Top 10 Most Frequent Tokens")
plt.xticks(rotation=45)
plt.show()


import seaborn as sns

sns.boxplot(x='vulnerability_type', y='code_length', data=df)
plt.xticks(rotation=45)
plt.title("Code Length vs Vulnerability Type")
plt.show()
